### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by xcornflowerx** [xcornflowerx/flowerbot#9]
Fix or handle `UnicodeEncodeError` when parsing arguments
```
flowerbot $ Traceback (most recent call last):
  File "scripts/flowerbot.py", line 454, in <module>
    main()
  File "scripts/flowerbot.py", line 451, in main
    bot.start()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/bot.py", line 340, in start
    super(SingleServerIRCBot, self).start()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 1198, in start
    self.reactor.process_forever()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 851, in process_forever
    consume(infinite_call(one))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/more_itertools/recipes.py", line 160, in consume
    deque(iterator, maxlen=0)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/jaraco/itertools.py", line 416, in <genexpr>
    return (f() for _ in itertools.repeat(None))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 832, in process_once
    self.process_data(in_)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 796, in process_data
    conn.process_data()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 280, in process_data
    self._process_line(line)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 313, in _process_line
    handler(arguments, command, source, tags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 349, in _handle_message
    self._handle_event(event)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 378, in _handle_event
    self.reactor._handle_event(self, event)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 928, in _handle_event
    result = handler.callback(connection, event)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/irc/client.py", line 1161, in _dispatcher
    method(connection, event)
  File "scripts/flowerbot.py", line 177, in on_pubmsg
    self.auto_streamer_shoutout(e)
  File "scripts/flowerbot.py", line 278, in auto_streamer_shoutout
    self.streamer_shoutout_message(user)
  File "scripts/flowerbot.py", line 252, in streamer_shoutout_message
    if str(game) == 'None' and not user in CUSTOM_USER_SHOUTOUTS.keys():
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2122' in position 19: ordinal not in range(128)```

**Comment by xcornflowerx** [comment]
resolved in pr #10
